name: Periodic Model Calibration

on:
  schedule:
    - cron: "0 0 * * *" #minutes, hours, day, month, day of week
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r Github_Labs/Lab2/requirements.txt

      - name: Generate and Store Timestamp
        run: |
          timestamp=$(date '+%Y%m%d%H%M%S')
          echo "$timestamp" > timestamp.txt
        id: timestamp

      - name: Check File Permissions
        run: |
          ls -l Github_Labs/Lab2/src/train_model.py

      - name: Set File Permissions
        run: |
          chmod +x Github_Labs/Lab2/src/train_model.py

      - name: Retrain Model
        run: |
          timestamp=$(cat timestamp.txt) # Use the timestamp in your training script
          python Github_Labs/Lab2/src/train_model.py --timestamp "$timestamp"

      - name: Evaluate Model and Log Metrics
        run: |
          timestamp=$(cat timestamp.txt) # Use the timestamp in your training script
          python Github_Labs/Lab2/src/evaluate_model.py  --timestamp "$timestamp" # Assuming you have a script for model evaluation
          # File is already created in metrics/ directory by the script
        continue-on-error: false # Continue even if evaluation fails

      - name: Store and Version the New Model
        run: |
          timestamp=$(cat timestamp.txt)
          model_filename="model_${timestamp}_dt_model.joblib"
          mv $model_filename $GITHUB_WORKSPACE/models/$model_filename

      - name: Commit and Push Changes
        run: |
          git config --global user.email "256461987+shptl7@users.noreply.github.com"
          git config --global user.name "shptl7"
          git add $GITHUB_WORKSPACE/metrics/$metrics_filename $GITHUB_WORKSPACE/models/$model_filename
          git commit -m "Add metrics and updated model"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
